server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
  http2:
    enabled: true
  port: 8080

management:
  health:
    mongo:
      enabled: true
endpoints:
  mongo:
    enabled=true:

spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}